services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
  
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    environment:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always
networks:
  inception:
    driver: bridge
volumes:
  db_data:
    driver: local