services:

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - 42-inception
    volumes:
      - data_db:/var/lib/mysql
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - 42-inception

networks:
  42-inception:
    driver: bridge

volumes:
  data_db:
    name: data_db
    driver: local
    driver_opts:
      type: none
      device: /home/ahamuyel/data/db
      o: bind
