services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    secrets:
      - db_root_password
      - db_user_password
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    networks:
      - inception
    secrets:
      - db_root_password
      - db_user_password
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html 
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    restart: always

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      device: /home/ahamuyel/data/db
      o: bind

  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      device: /home/ahamuyel/data/wp
      o: bind
      
