# version: "3.9"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html 
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
  wp_data:
    driver: local
